"""empty message

Revision ID: 501e4020ec57
Revises: 89b209dc69a6
Create Date: 2023-04-13 23:16:57.971651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501e4020ec57'
down_revision = '89b209dc69a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_column('webpage')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_column('webpage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webpage', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webpage', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###
